version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: microfinance-banks
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: microfinance-banks

	microfinance-banks:
		build: .
		image: chamaconekt/microfinance-banks
		links:
		- postgres
		container_name: microfinance-banks
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- microfinance-banks
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/microfinance-banks-nginx/nginx.conf
		depends_on:
			- microfinance-banks
		ports:
			- 80:80
		volumes_from:
			- microfinance-banks

volumes:
	microfinance-banks-static-files:
		driver:local